/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AutorRouteImport } from './routes/autor'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as LivroRouteImport } from './routes/livro'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as CapitulosSlugRouteImport } from './routes/capitulos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorRoute = AutorRouteImport.update({
  id: '/autor',
  path: '/autor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroRoute = LivroRouteImport.update({
  id: '/livro',
  path: '/livro',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const CapitulosSlugRoute = CapitulosSlugRouteImport.update({
  id: '/capitulos/$slug',
  path: '/capitulos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRouteWithChildren
  '/autor': typeof AutorRoute
  '/contato': typeof ContatoRoute
  '/livro': typeof LivroRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/capitulos/$slug': typeof CapitulosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRouteWithChildren
  '/autor': typeof AutorRoute
  '/contato': typeof ContatoRoute
  '/livro': typeof LivroRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/capitulos/$slug': typeof CapitulosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRouteWithChildren
  '/autor': typeof AutorRoute
  '/contato': typeof ContatoRoute
  '/livro': typeof LivroRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/capitulos/$slug': typeof CapitulosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/admin'
    | '/autor'
    | '/contato'
    | '/livro'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/usuarios'
    | '/capitulos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/admin'
    | '/autor'
    | '/contato'
    | '/livro'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/usuarios'
    | '/capitulos/$slug'
  id:
    | '__root__'
    | '/'
    | '/acesso'
    | '/admin'
    | '/autor'
    | '/contato'
    | '/livro'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/usuarios'
    | '/capitulos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRoute: typeof AcessoRoute
  AdminRoute: typeof AdminRouteWithChildren
  AutorRoute: typeof AutorRoute
  ContatoRoute: typeof ContatoRoute
  LivroRoute: typeof LivroRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  CapitulosSlugRoute: typeof CapitulosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor': {
      id: '/autor'
      path: '/autor'
      fullPath: '/autor'
      preLoaderRoute: typeof AutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro': {
      id: '/livro'
      path: '/livro'
      fullPath: '/livro'
      preLoaderRoute: typeof LivroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/capitulos/$slug': {
      id: '/capitulos/$slug'
      path: '/capitulos/$slug'
      fullPath: '/capitulos/$slug'
      preLoaderRoute: typeof CapitulosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsuariosRoute: typeof AdminUsuariosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsuariosRoute: AdminUsuariosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRoute: AcessoRoute,
  AdminRoute: AdminRouteWithChildren,
  AutorRoute: AutorRoute,
  ContatoRoute: ContatoRoute,
  LivroRoute: LivroRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  CapitulosSlugRoute: CapitulosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
